name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
        name: Setup Ruby

      - run: bundle install
        name: Install dependencies

      - run: bundle exec jekyll build
        name: Build Jekyll site

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site
        name: Upload artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: actions/download-artifact@v2
        with:
          name: site
        name: Download artifacts

      - run: rsync -r _site/ ./public/
        name: Sync files

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        name: Deploy to GitHub Pages
